config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "events#index"

  get 'searchtag/:tag', to: 'events#index', as: :tag

  resources :events do
    get :join, to: 'events#join', as: :join
    get :accept_request, to: 'events#accept_request', as: 'accept_request'
    get :reject_request, to: 'events#reject_request', as: 'reject_request'
  end

  get :my_events, to: 'events#my_events', as:'my_events'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :user
	belongs_to :event

	scope :accepted, -> {where(state: 'accepted')}
	scope :pending, -> {where(state: 'request_sent')}
	scope :rejected, -> {where(state: 'rejected')}



	#attr_accessor :state
	include Workflow
	
	workflow_column :state

	workflow do
		state :request_sent do
			event :accept, :transitions_to => :accepted
			event :reject, :transitions_to => :rejected
		end
		state :accepted
		state :rejected
	end
 
	def self.join_event(user_id, event_id, state)
		self.create(user_id: user_id, event_id: event_id, state: state)
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	
	belongs_to :organizers, class_name: "User"

	has_many :taggings
	has_many :tags, through: :taggings

	has_many :attendances
	has_many :users, :through => :attendances
  
	  def all_tags=(names)
	    self.tags = names.split(",").map do |t|
	      Tag.where(name: t.strip).first_or_create!
	    end
	  end

	def all_tags
		tags.map(&:name).join(", ")
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).events
	end

	def self.tag_counts
		Tag.select("tags.name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end

	def event_owner(organizer_id)
		User.find_by id: organizer_id
	end

	def self.pending_requests(event_id)
		Attendance.pending.where(event_id: event_id)
	end
  
	def self.show_accepted_attendees(event_id)
		Attendance.accepted.where(event_id: event_id)
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"

  has_many :attendances
  has_many :events, :through => :attendances

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :accept_request, :reject_request]
  before_action :event_owner!, only: [:edit, :update, :destroy, :accept, :reject]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  
  respond_to :html, :json

  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
    #respond_with(@events)
  end

  def show
    @event_owner = @event.event_owner(@event.organizer_id)
    @attendees = Event.show_accepted_attendees(@event.id)
    @pending_requests = Event.pending_requests(@event.id)
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def join
    @attendance = Attendance.join_event(current_user.id, params[:event_id], 'request_sent')
    @attendance.save
    #respond_with @attendance

     respond_to do |format|
       format.html { redirect_to(events_path, :notice => 'Request Sent') }
     end
  end

  def create
    @event = current_user.organized_events.new(event_params)
    respond_to do |format|

      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.'}
        format.json { render action: 'show', status: :created, location: @event}
      else
        format.html { render action: 'new'}
        format.json { render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def accept_request
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    
    #'Application Accepted' if @attendance.save
    @attendance.accept!

    redirect_to(@event)
  end

  def reject_request
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.reject!
    #'Application Rejected' if @attendance.save
    redirect_to(@event)

     
     #format.html { redirect_to @event, notice: 'Rejected.'}
  end

  def my_events
    @events = current_user.organized_events
  end

  private
    def set_event
      #@event = Event.find(params[:id])
      if params[:event_id].present?
        @event = Event.friendly.find(params[:event_id])
      else
        @event =Event.friendly.find(params[:id])
      end
    end

    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id, :all_tags, :user_id)
    end

    def event_owner!
      authenticate_user!
      if @event.organizer_id != current_user.id
        redirect_to events_path
        flash[:notice] = 'You do not have enough permissions to do this'
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size - 1)
			yield(tag, classes[index.round])
		end
	end

	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		"http://gravatar.com/avatar/#{gravatar_id}.png"
	end
	

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :organizer_id %><br>
    <%= f.number_field :organizer_id %>
  </div>
  <div class="field">
    <%= f.label :all_tags, "List All Tags, separate each tag by a comma" %><br/>
    <%= f.text_field :all_tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_tag_cloud.html.erb
<div class="col-lg-4">
  <h3>Search Tags</h3>
  <div>
      <%  tag_cloud Event.tag_counts, %w(css1 css2 css3 css4) do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render "tag_cloud" %>

<h1>Listing events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= l event.start_date, :format => :date_format %></td>
        <td><%=  l event.end_date , :format => :date_format%></td>

        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.organizer_id %></td>
        <td><%= link_to 'Show', event, :class => "btn btn-primary btn-small" %></td>
        <td><%= link_to 'Edit', edit_event_path(event.id), :class => "btn btn-success btn-small" %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/my_events.html.erb
<h1>Listing events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%=  event.start_date %></td>
        <td><%=  event.end_date %></td>

        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.organizer_id %></td>
        <td><%= link_to 'Show', event, :class => "btn btn-primary btn-small" %></td>
        <td><%= link_to 'Edit', edit_event_path(event.id), :class => "btn btn-success btn-small" %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>


<%= render "tag_cloud" %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag avatar_url(@event_owner) %>
       <%= @event_owner.email %>
</p>
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>
<p><strong>Tags:</strong>
  <%=raw @event.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %><br/><br/>

</p>
<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @event.organizer_id %>
</p>
<p>
<% if user_signed_in? && @event.organizer_id == current_user.id %>
<label>Join Requests</label>
<% if @pending_requests.present? %>
  <% @pending_requests.each do |p| %>
    <%= image_tag avatar_url(p.user) %>
    <%= p.user.email %>
    <%= link_to 'Accept', event_accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class => "btn btn-success btn-small" %>
    <%= link_to 'Reject', event_reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class => "btn btn-danger btn-small" %>
  <% end %>
<% else %>
  <p> No Pending Requests for this </p>
<% end %>
<% end %>
</p>

<p>
<label>Attendees</label>
<% @attendees.each do |a| %>
  <%= image_tag avatar_url(a.user) %>
  <%= a.user.email %>
<% end %>
</p>




<p>
  <%= link_to "Join", event_join_path(:event_id => @event.id), :class => "btn btn-success btn-small" %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventst</title>
      <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
	<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="navbar navbar-default navbar-static-top">
	 <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

		<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">	
		<% if user_signed_in? %>
			<p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p>
		  
		  <li><%= link_to 'My Events', my_events_path, :class => 'navbar-link' %> </li>
		  <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
		  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
		<% else %>
		  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
		  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
		<% end %>
		</ul>
		</nav>
		</div>
	</header>

	<div class="container">
		<div class="row">
			
			<div class="col-lg-2">
				
			</div>
			<div class="col-lg-9">
				<p id="notice"><%= notice %></p>
				<%= yield %>
			</div>
		</div>
	</div>
<footer>
	  <div class="container">
	    Rails Girls 2014
	  </div>
	</footer>
	<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>